### ISSUE TITLE
add certificate to the map and api

### ISSUE THREAD

**Issue by aumanjoa** [daumann/chronas#26]
https://letsencrypt.org/

Jetstack (https://github.com/jetstack/cert-manager). Der verwaltet die Certs sehr gut automatisiert in K8S und bezieht die Certs von Letsencrypt.

https://runnable.com/blog/how-to-use-lets-encrypt-on-kubernetes
https://github.com/jetstack/kube-lego

**Comment by daumann** [comment]
die haben wahrscheinlich https als requirement?
