### ISSUE TITLE
Automatic deployment build broken

### ISSUE THREAD

**Issue by daumann** [daumann/chronas#6]
It seems the data is not loaded correctly in production environment.

`Uncaught ReferenceError: t is not defined` in the logs

**Comment by aumanjoa** [comment]
please review on http://chronasdev.azurewebsites.net/#/ its the free pricing so it could be slow

**Comment by daumann** [comment]
still to fix: fonts missing for mapbox (no text labels) + timeline is not showing up (vis.js dependency)

**Comment by aumanjoa** [comment]
is this still happening?
